"""
Phase 1 slip generation helper script for Philippine Trench PTHA.

This script uses the configuration defined in
`philippine_trench_config.PHILIPPINE_TRENCH_PTHA_CONFIG` and the
`RUPTURE_SCENARIOS` dictionary to drive stochastic slip sampling for each
magnitude scenario.  Slip realizations are generated by
`slip_sampler.StochasticSlipGenerator` using parameters extracted from the
thesis (covariance, correlation length, etc.) and the Heidarzadeh CSV files.

Usage:
    python phase1_generate.py

The output arrays are saved automatically into the `output/slip_samples`
directory using the generator's built-in mechanism.

The subfault discretization is chosen such that the total number of
subfaults is approximately equal to `slip_params.n_subfaults` (400 by
default).  A simple geometric formula is used to pick the subfault size
in kilometres.
"""

import numpy as np
from pathlib import Path
import sys

# make sure modules in same package can be imported when script is run directly
sys.path.insert(0, str(Path(__file__).parent))

from slip_sampler import StochasticSlipGenerator
from philippine_trench_config import PHILIPPINE_TRENCH_PTHA_CONFIG, RUPTURE_SCENARIOS


def compute_subfault_size(length_km, width_km, target_n):
    """Compute a subfault size (km) so that n_along * n_down ~ target_n.

    We assume a regular grid and choose the size based on the geometric mean
    of the two dimensions:
        area = length * width
        size = sqrt(area / target_n)

    The resulting grid may not fit exactly; the generator recomputes the
    dimensions internally to ensure an integer number of subfaults.
    """
    return np.sqrt((length_km * width_km) / target_n)


def main():
    cfg = PHILIPPINE_TRENCH_PTHA_CONFIG
    slip_cfg = cfg.slip_params
    # clean out any previous RQMC samples to avoid confusion
    import shutil
    old_dir = Path("output") / "slip_samples"
    if old_dir.exists():
        print(f"Removing old RQMC slip samples at {old_dir}")
        shutil.rmtree(old_dir)
    # only generate slips for magnitudes that appear in the hypothetical CSV
    csv_path = Path("data") / "fault_geometry" / "heidarzadeh_2025_table3.csv"
    if not csv_path.exists():
        raise FileNotFoundError(f"Fault geometry CSV not found: {csv_path}")

    # read available magnitudes from the CSV (format: "Mw 8.0", etc.)
    import pandas as pd
    available = pd.read_csv(csv_path)["Hypothetical scenario"].str.replace("Mw ", "").astype(float).tolist()

    n_samples = slip_cfg.n_samples_per_magnitude[0]
    seed = 42  # fixed for reproducibility

    print("Phase 1: Slip generation")
    print("============================")
    print(f"Using slip parameters: {slip_cfg}")
    print(f"Available magnitudes in CSV: {available}")
    print(f"Generating {n_samples} samples per available scenario, seed={seed}\n")

    for name, scenario in RUPTURE_SCENARIOS.items():
        mag = scenario.magnitude
        if mag not in available:
            print(f"Skipping scenario {name} (Mw {mag}) – not present in CSV")
            continue

        print(f"Processing scenario {name} (Mw {mag})")

        # compute subfault size to yield approx slip_cfg.n_subfaults
        subfault_size = compute_subfault_size(scenario.length_km,
                                              scenario.width_km,
                                              slip_cfg.n_subfaults)
        print(f"  target subfault count: {slip_cfg.n_subfaults},"
              f" computed size: {subfault_size:.2f} km")

        # construct generator with KL sampling enabled
        generator = StochasticSlipGenerator(
            magnitude=mag,
            fault_params_csv=csv_path,
            subfault_size_km=subfault_size,
            covariance_model=slip_cfg.covariance_model,
            correlation_length_km=slip_cfg.correlation_length_km,
            use_kl=True,  # use Karhunen–Loève eigenbasis
        )

        # generate and save each realization
        output_dir = Path("output") / "slip_samples" / f"Mw{mag:.1f}"
        output_dir.mkdir(parents=True, exist_ok=True)

        samples = []
        for idx in range(n_samples):
            slip = generator.generate_rqmc_sample(idx, seed=seed)
            samples.append(slip)
            out_path = output_dir / f"slip_Mw{mag:.1f}_sample{idx}.npy"
            np.save(out_path, slip)
        print(f"  generated and saved {len(samples)} slip realizations to {output_dir}")
        if samples:
            print(f"    example shape: {samples[0].shape}")
        print()

    print("Phase 1 generation complete. Slip arrays are stored in output/slip_samples.")


if __name__ == "__main__":
    main()
